version: '3.8'

services:
  react-app:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Exponiendo el servicio Vite en un puerto diferente
    depends_on:
      - db
      - api

  api:
    build:
      context: ./back
      dockerfile: Dockerfile
    environment:
      DHOST: db
      DUSER: user
      NAME: mydatabase
      PASSWORD: password
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  db_data:
